#!/usr/bin/env ruby

require 'highline/import'

require './gab'
require './timesheets'

today = Time.now

if today.monday?
  due_date = today
else
  days_until_sunday = (7 - today.wday) % 7
  due_date = Time.at(today.to_i + days_until_sunday * 86400)
end

deadline = due_date.strftime("%d/%m/%Y")

user = ask("peoplesoft user: ")
pass = ask("peoplesoft pass: ") { |q| q.echo = "*" }
puts "Finding bad guys for #{deadline}..."
ts = ThoughtWorks::Timesheets.new(user, pass)
badguys = ts.lates(deadline)
puts "Found #{badguys.size} bad guys..."

user = ask("gab user: ")
pass = ask("gab pass: ") { |q| q.echo = "*" }
gab = ThoughtWorks::Gab.new(user, pass)

puts "GPS'ing all up on 'em..."
badguys.each do |b|
  # A couple people have unicode craziness, and either oracle or gab are
  # blowing chunks when they encounter it. Just one off them here for now.
  b = b.gsub("\xea", 'e').gsub("\xf6", 'o')

  name, number_and_email = gab.search(b).first
  number, email = *number_and_email
  puts "#{b} : #{email} -> #{number}"
end
