#!/usr/bin/env ruby

require 'json'
require 'logger'
require 'trollop'

require './gab'
require './timesheets'
require './config_helper'

opts = Trollop::options do
  banner <<-EOS
usage: tec [OPTIONS...]
  EOS

  opt :region, "Where in the world is Carme... the bad guys with a time warrant on their heads",
    :default => "us"
  opt :debug, "There's never enough time. Never enough for what? To satisfy a [developer who wants to see the logs]"
end

Mechanize::log = Logger.new($stderr) if opts[:debug]

today = Time.now

if today.monday?
  due_date = Time.at(today.to_i - 86400)
else
  days_until_sunday = (7 - today.wday) % 7
  due_date = Time.at(today.to_i + days_until_sunday * 86400)
end

deadline = due_date.strftime("%d/%m/%Y")

user = APP_CONFIG['twuser'] 
pass = ENV['TWPASS']
$stderr.puts "Deadline: #{deadline}..."
ts = ThoughtWorks::Timesheets.new(user, pass)
badguys = ts.lates(deadline, opts[:region])
$stderr.puts "#{badguys.size} timesheets not submitted yet"

user = APP_CONFIG['twuser']
pass = ENV['TWPASS']
gab = ThoughtWorks::Gab.new(user.gsub(/@thoughtworks\.com/, ""), pass)

badguys.each do |b|
  # A couple people have unicode craziness, and either oracle or gab are
  # blowing chunks when they encounter it. Just one off them here for now.
  b = b.gsub("\xea", 'e').gsub("\xf6", 'o').gsub("\xED", 'i').gsub("\xE1", 'i')

  name, number_and_email = gab.search(b, opts[:region]).first
  number, email = *number_and_email
  puts ({"name" => b, "email" => email, "mobile" => number}.to_json)
end

